# Generated by Django 3.1.12 on 2025-01-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='electricitybill',
            table='electricityBill',
        ),
        migrations.AlterModelTable(
            name='rent',
            table='rent',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='tenant',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userproperties',
            table='userProperties',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='userRole',
        ),
        migrations.AlterModelTable(
            name='userrolelink',
            table='userRoleLink',
        ),
    ]
