# Generated by Django 5.1.5 on 2025-01-27 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_city_name_city_cityname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='myapp.state'),
        ),
    ]
