# Generated by Django 5.1.5 on 2025-01-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userrolelink_role_alter_userrolelink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='room',
            field=models.ForeignKey(db_column='roomId', on_delete=django.db.models.deletion.CASCADE, to='myapp.rooms'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(db_column='roomId', on_delete=django.db.models.deletion.CASCADE, to='myapp.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='property',
            field=models.ForeignKey(db_column='userPropertiesId', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='myapp.userproperties'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(db_column='userPropertiesId', on_delete=django.db.models.deletion.CASCADE, to='myapp.userproperties'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(db_column='roomId', on_delete=django.db.models.deletion.CASCADE, to='myapp.rooms'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(db_column='cityId', on_delete=django.db.models.deletion.CASCADE, to='myapp.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='city',
            field=models.ForeignKey(db_column='cityId', on_delete=django.db.models.deletion.CASCADE, to='myapp.city'),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='state',
            field=models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='myapp.user'),
        ),
    ]
