# Generated by Django 5.1.5 on 2025-01-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_electricitybill_room_alter_rent_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, related_name='stateCities', to='myapp.state'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='room',
            field=models.ForeignKey(db_column='roomId', on_delete=django.db.models.deletion.CASCADE, related_name='electricityBills', to='myapp.rooms'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(db_column='roomId', on_delete=django.db.models.deletion.CASCADE, related_name='rentRooms', to='myapp.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='property',
            field=models.ForeignKey(db_column='userPropertiesId', on_delete=django.db.models.deletion.CASCADE, related_name='propertyRooms', to='myapp.userproperties'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(db_column='userPropertiesId', on_delete=django.db.models.deletion.CASCADE, related_name='tenantProperties', to='myapp.userproperties'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(db_column='roomId', on_delete=django.db.models.deletion.CASCADE, related_name='tenantRooms', to='myapp.rooms'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='tenantUsers', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userProperties', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='userrolelink',
            name='role',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, related_name='userRoleLinks', to='myapp.userrole'),
        ),
        migrations.AlterField(
            model_name='userrolelink',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userRoleLinks', to='myapp.user'),
        ),
    ]
